version: '3'
services:
    # es:
    #     image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    #     container_name: es
    #     environment:
    #         - xpack.security.enabled=false
    #         - discovery.type=single-node
    #     ulimits:
    #       memlock:
    #         soft: -1
    #         hard: -1
    #     volumes:
    #       - ./elastic:/usr/share/elasticsearch/data:delegated
    #     ports:
    #       - 9200:9200
    nginx:
        image: ${nginx_version}
        container_name: ${nginx_container}
        restart: always
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs/nginx:/var/log/nginx
        links:
            - php
    php:
        build: ./images/php
        container_name: ${php_container}
        restart: always
        links:
            - db
        volumes:
            - ./www:/var/www
            - ./images/php/php.ini:/usr/local/etc/php/conf.d/40-custom.ini
        ports:
            - 9001
        environment:
            XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1 remote_port=9001"
            PHP_IDE_CONFIG: "serverName=Docker"
    db:
        platform: linux/x86_64
        image: ${mysql_version}
        container_name: ${mysql_container}
        command: --default-authentication-plugin=mysql_native_password
        command: --sql_mode=""
        restart: always
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql:delegated
            - ./config/my.cnf:/etc/mysql/my.cnf
        environment:
            MYSQL_ROOT_PASSWORD: ${mysql_root_password}
    # adminer:
    #     image: adminer
    #     container_name: adminer
    #     restart: always
    #     ports:
    #         - 8080:8080
    phpmyadmin:
        image: phpmyadmin
        restart: always
        container_name: phpmyadmin
        ports:
            - 8080:8080
        environment:
            - PMA_ARBITRARY=1
            - PMA_ABSOLUTE_URI=http://phpmyadmin.localhost/
            - PMA_HOST=db
    # mongo:
    #     image: ${mongodb_version}
    #     container_name: ${mongodb_container}
    #     restart: always
    #     volumes:
    #         - ./mongodb:/data/db
    #     environment:
    #         MONGO_INITDB_ROOT_USERNAME: ${mongo_root_user}
    #         MONGO_INITDB_ROOT_PASSWORD: ${mongo_root_password}
    # mongo-express:
    #     image: ${mongo_express_version}
    #     container_name: ${mongo_express}
    #     restart: always
    #     ports:
    #         - 8081:8081
    #     environment:
    #         ME_CONFIG_MONGODB_ADMINUSERNAME: ${mongo_root_user}
    #         ME_CONFIG_MONGODB_ADMINPASSWORD: ${mongo_root_password}
networks:
    default:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 192.168.22.0/24
